name: Test, Lint, Coverage, and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'setup.py'
      - 'asrpy/**'
      - 'tests/**'
      - '.github/workflows/publish.yml'

jobs:
  test:
    name: Test, Lint, and Coverage on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov flake8

      - name: Run linting with flake8
        run: flake8 asrpy/ tests/

      - name: Run unit tests with coverage
        run: |
          pytest --cov=asrpy --cov-report=xml tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true

  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    needs: test  # Only run if all test matrix jobs pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* -u __token__ -p "$TWINE_PASSWORD"
